### ISSUE TITLE
Responsive layout: footer

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#5]
Если убрать все @media стили с footer-item, а управлять расположением элементов с помощью `justify-content` на элементе `footer-main` - можно добиться неплохих результатов.
Пример:

```css
.footer-item {
 /* убираем стили */
}

.footer-main {
    display: flex;
    flex-flow: row wrap;
    justify-content: space-between;
}
@media (max-width: 800px)
.footer-main {
    text-align: center;
    justify-content: space-around;
}

@media (max-width: 600px)
.footer-main {
    text-align: center;
    justify-content: space-between;
}

```

Flexbox очень мощная штука, и сложные вещи в нем можно сделать намного проще.
